dist: xenial
sudo: required
language: python
cache:
  - apt
  - pip
addons:
  apt:
    packages:
      - openjdk-8-jdk
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
install:
  - pip install poetry tox awscli
before_script:
  - ./scripts/test_data/upload_test_data.sh
script:
  - tox
# after_success:
#   - ./scripts/test_data/delete_test_data.sh
